### ISSUE TITLE
Comments not being ignored during evaluating

### ISSUE THREAD

**Issue by zygurt** [noahingham/extempore-atom#5]
I'm finding that when I comment a line with a greater number of left or right brackets, that the bracket matching ignores the comment character and matches into the comment.  This then means that when parsing the code during evaluation it uses code within the comments.

**Comment by noahingham** [comment]
Is the issue with bracket highlighting or with evaluation?

If its with evaluation, it will show `ERROR: s-expr parser failed` at the bottom of the editor - this should have been fixed in 0.3.1 but it may not be checking for all cases of comments. Could you could paste example code with a comment triggering this?

If it's with bracket highlighting - Atom currently highlight matches brackets in comments for all languages: https://github.com/atom/bracket-matcher/issues/78

**Comment by zygurt** [comment]
The issue is with evaluating.
This code works:
(bind-func brackets
  (lambda ()
    (let ((n:i64 0)
          (temp:i64 0))
      (dotimes (n 10)
        (set! temp (* n n))
        (set! temp (+ n n)))
    )))

This code gives back the s-expr parser failed error.
(bind-func brackets
  (lambda ()
    (let ((n:i64 0)
          (temp:i64 0))
      (dotimes (n 10)
        (set! temp (* n n))) ; Added bracket to this line to close the dotimes.
        ;(set! temp (+ n n)))
    )))

This code works:
(bind-func brackets
  (lambda ()
    (let ((n:i64 0)
          (temp:i64 0))
      (dotimes (n 10)
        (set! temp (* n n)))
        ;(set! temp (+ n n))  ; bracket deleted from the end of this line.
    )))

**Comment by noahingham** [comment]
This should be fixed now - I usually use two semicolons for comments and forgot to test for single `;` comments. Thanks for bringing it to my attention.

**Comment by zygurt** [comment]
Thank-you muchly.
